#!/bin/sh
LIBS=$HOME/http/scriptcache
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -cp $LIBS $0 $@
!#

import doom._
import ninthdrug.http._

val server = new WebServer(
  ServerConfig(
    Config.get("ninthdrug.http.scriptcache"),
    List(
      SiteConfig("localhost_8080", "localhost", 8080, "", HOME + "/www/localhost_8080")
    )
  )
)

server.run()
