#!/bin/sh
LIBS=
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -cp $LIBS $0 $@
!#

import doom._
  
val domain = ConfigCache.getDomain("asset_wls_dev")
val host = domain.managedservers(0).machinename
val cmd = StartNodeManager(domain, host)
println(cmd)
cmd.print
