#!/bin/sh
LIBS=
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -cp $LIBS $0 $@
!#

import doom._

val domain = Domain(
  name = "poc_osb_local",
  domaintype = "osb",
  servers = List(
    Server( 
      name = "poc_osb_local_admin_server",
      servertype = "admin",
      address = "localhost",
      port = 7200
    )
  ),
  clusters = List(
    Cluster(
      name = "poc_osb_local_cluster",
      servers = List(
        Server(
          name = "poc_osb_local_server_1",
          address = "localhost",
          port = 7210,
          machinename = "localhost"
        )
      )
    )
  ) 
)  

InitDomainOffline(domain).print
