#!/bin/sh
LIBS=""
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -save -cp $LIBS $0 $@
!#

import doom._

def prompt(n : Int, name : String) : String = {
    if (args.length < n + 1) {
        val value = Console.readLine(name + ": ")
        value
    } else {
        args(n)
    }
}

var userid = prompt(0, "userid")
var password = prompt(1, "password")

println("userid: " + userid)
println("password: " + password)

CredentialCache.setDoomPassword(userid, password)
