#!/bin/sh
LIBS=""
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -save -cp $LIBS $0 $@
!#

import doom._
import ninthdrug.command._
import ninthdrug.mail.Mail

var userid = prompt(args, 0, "userid")

val user = ConfigCache.getUser(userid)
val newpassword = Auth.generatePassword
CredentialCache.setDoomPassword(userid, newpassword)

Sh("sync_doom_user " + userid).print

Mail.mail(
  "doom@" + fullhostname,
  user.email,
  "Your doom password has been reset.",
  "Your new doom password is: " + newpassword
)
