#!/bin/sh
LIBS=""
for JAR in $DOOMHOME/lib/*.jar
do
  LIBS=$LIBS:$JAR
done
exec scala -save -cp $LIBS $0 $@
!#

import doom._
val pids = psgrep("doom.server.DoomServer")
for (pid <- pids) {
  kill_process_tree(pid)
}
