#!/bin/sh
LIBS=""
for jar in $DOOMHOME/lib/*.jar
do
    LIBS=$LIBS:$jar
done
exec scala -save -cp "$LIBS" $0 $@
!#

import doom._
import ninthdrug.command._

for (domain <- ConfigCache.domains) {
  Sh("sync_domain_users " + domain.name).print
}
